// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ_rwa9lXjA5b9sGCJS9LPl6fbH6ffVSs',
    appId: '1:307859235376:android:6717c493edc986266143f5',
    messagingSenderId: '307859235376',
    projectId: 'puzzle-quest-c5c7e',
    databaseURL: 'https://puzzle-quest-c5c7e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-quest-c5c7e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafprsJop6rz0ICo-ol_KuwY766iZF6P8',
    appId: '1:307859235376:web:b7c778dc5e211a7d6143f5',
    messagingSenderId: '307859235376',
    projectId: 'puzzle-quest-c5c7e',
    authDomain: 'puzzle-quest-c5c7e.firebaseapp.com',
    databaseURL: 'https://puzzle-quest-c5c7e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-quest-c5c7e.firebasestorage.app',
    measurementId: 'G-4N85EPT4ZC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjejLVmoDPL2T2BGs24vxu8GZ2639QQZY',
    appId: '1:307859235376:ios:67acbe7a9b2f280d6143f5',
    messagingSenderId: '307859235376',
    projectId: 'puzzle-quest-c5c7e',
    databaseURL: 'https://puzzle-quest-c5c7e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-quest-c5c7e.firebasestorage.app',
    iosBundleId: 'com.example.puzzleQuest',
  );

}